#!/usr/bin/env bash

set -e

cd "$(dirname $0)"

if [ "$1" == "" ] && [ "$(git rev-parse --abbrev-ref HEAD)" == "main" ]; then
  echo "usage $0 <pr-number>"
  exit 1
fi

if [ "$1" != "" ]; then
  gh pr checkout $1
fi

npm i
npm run all
git add dist/index.js*
git commit -m "run all"
git push

git switch main
git pull
