name: Jira Estimate Sync
on:
  issues:
    types:
    - opened
    - edited
    - deleted
    - labeled
    - unlabeled

  pull_request:
    branches:
    - test
    types:
    - labeled
    - unlabeled
    - opened
    - edited

jobs:
  sync-estimates:
    runs-on: ubuntu-latest

    steps:
    - uses: MichaelSp/jira-estimates@test
      with:
        jira-url: ${{ secrets.JIRA_HOST }}
        jira-username: ${{ secrets.JIRA_USERNAME }}
        jira-password: ${{ secrets.JIRA_PASSWORD }}
        jira-project-regex-pattern: HSOBRD-\d+
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}